/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorVistaUsuario;
import modelos.Pelicula;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author JuanCGallo
 */
public class VistaUsuario extends javax.swing.JFrame implements ActionListener {

	/**
	 * Creates new form VistaUsuario
	 */

	ControladorVistaUsuario controladorVistaUsuario;
	JButton[][] pelis;
	JLabel[][] titulos;
	JLabel[][] puntuaciones;
	int filas;

	public VistaUsuario() {
		initComponents();
		setLocationRelativeTo(this);
		this.controladorVistaUsuario = new ControladorVistaUsuario();
		filas = controladorVistaUsuario.getFilas();
		pelis = new JButton[filas][];
		titulos = new JLabel[filas][];
		puntuaciones = new JLabel[filas][];
		dibujarPeliculas();
	}


	private void dibujarPeliculas() {

		int separadoX = 20;
		int separadoY = 30;
		int ancho = 120;
		int alto = (int) (((double) ancho) * 1.6);
		int margen = 20;
		int peliculasPorFila = controladorVistaUsuario.getPELICULAS_POR_FILA();
		int cantidadPeliculas = controladorVistaUsuario.getCantidadPeliculas();

		for (int i = 0; i < pelis.length; i++) {
			int len = (i == pelis.length-1) ? (cantidadPeliculas - (filas-1) * peliculasPorFila) : peliculasPorFila;
			System.out.println("pelis.length:" + pelis.length + " len:" + len);
			pelis[i] = new JButton[len];
			titulos[i] = new JLabel[len];
			puntuaciones[i] = new JLabel[len];
			for (int j = 0; j < len; j++) {
				pelis[i][j] = new JButton();
				titulos[i][j] = new JLabel();
				puntuaciones[i][j] = new JLabel();
				// setbounds (posX, posY, ancho, alto)
				pelis[i][j].setBounds(
						(ancho + margen) * j + separadoX,
						(alto + margen) * i + separadoY,
						ancho, alto
				);
				int ALTO_TITULO = 15;
				double RATIO_ANCHO = 0.8;
				titulos[i][j].setBounds(
						(ancho + margen) * j + separadoX,
						(alto + margen) * i + separadoY + alto * (i + 1),
						(int) ((double) ancho * (RATIO_ANCHO)),
						ALTO_TITULO
				);
//				titulos[i][j].setOpaque(true);
				titulos[i][j].setText(controladorVistaUsuario.getTituloByIdx(i+j));
				titulos[i][j].setBackground(Color.RED);
				titulos[i][j].setHorizontalAlignment(SwingConstants.CENTER);
				titulos[i][j].setVerticalAlignment(SwingConstants.CENTER);
				puntuaciones[i][j].setBounds(
						(ancho + margen) * j + separadoX + (int) ((double) ancho * RATIO_ANCHO),
						(alto + margen) * i + separadoY + alto * (i + 1),
						(int) ((double) ancho * (1 - RATIO_ANCHO)),
						ALTO_TITULO
				);
//				puntuaciones[i][j].setOpaque(true);
				puntuaciones[i][j].setText(String.valueOf(controladorVistaUsuario.getPuntuacionByIdx(i+j)));
				puntuaciones[i][j].setBackground(Color.BLUE);
				puntuaciones[i][j].setForeground(Color.WHITE);
				puntuaciones[i][j].setHorizontalAlignment(SwingConstants.CENTER);
				puntuaciones[i][j].setVerticalAlignment(SwingConstants.CENTER);
				try {
					Image img = ImageIO.read(getClass().getResource("/img/terminator_2.jpg"));
					img = img.getScaledInstance(ancho, alto, Image.SCALE_DEFAULT);
					pelis[i][j].setIcon(new ImageIcon(img));
				} catch (Exception ex) {
					System.out.println(ex);
				}
				pelis[i][j].addActionListener(this);
				panelPeliculas.add(pelis[i][j]);
				panelPeliculas.add(titulos[i][j]);
				panelPeliculas.add(puntuaciones[i][j]);
			}
		}

		// Solución de Gemini :')
		int anchoPanel = peliculasPorFila * (ancho + margen) + 2 * separadoX;
		int altoPanel = filas * (alto + margen) + 2 * separadoY;
		panelPeliculas.setPreferredSize(new Dimension(anchoPanel, altoPanel));
		panelPeliculas.revalidate();
		jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
	}



	@Override
	public void actionPerformed(ActionEvent e) {
		int peliculasPorFila = controladorVistaUsuario.getPELICULAS_POR_FILA();
		for(int i = 0; i < pelis.length; i++) {
			for(int j = 0; j < pelis[i].length; j++) {
				if(e.getSource().equals(pelis[i][j])) {
					Pelicula pelicula = controladorVistaUsuario.entregarPelicula(i * peliculasPorFila + j);
					System.out.println(pelicula);
					VistaPelicula vistaPelicula = new VistaPelicula(pelicula);
					vistaPelicula.setVisible(true);
					this.dispose();
				}
			}
		}
	}



	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPeliculas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHistorialCompras = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout panelPeliculasLayout = new javax.swing.GroupLayout(panelPeliculas);
        panelPeliculas.setLayout(panelPeliculasLayout);
        panelPeliculasLayout.setHorizontalGroup(
            panelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        panelPeliculasLayout.setVerticalGroup(
            panelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelPeliculas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("BlockCluster");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHistorialCompras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHistorialCompras.setText("Ver Historial de Compras");
        btnHistorialCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialComprasActionPerformed(evt);
            }
        });

        btnCarrito.setText("Ver Carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79)
                        .addComponent(btnCarrito)
                        .addGap(59, 59, 59)
                        .addComponent(btnHistorialCompras)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHistorialCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarrito))
                        .addGap(12, 12, 12)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistorialComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialComprasActionPerformed
		VistaHistorialCompras vistaHistorialCompras = new VistaHistorialCompras();
		vistaHistorialCompras.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_btnHistorialComprasActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
		VistaCarrito vistaCarrito = new VistaCarrito();
		vistaCarrito.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_btnCarritoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VistaUsuario().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnHistorialCompras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPeliculas;
    // End of variables declaration//GEN-END:variables
}
