/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import Controllers.ControllerAsignMovies;
import Models.Movie;

/**
 *
 * @author Dell
 */
public class AsignMoviesView extends javax.swing.JFrame {

    /**
     * Creates new form AsignMoviesView
     */
	private ControllerAsignMovies viewController;
	private JTextField[][] inputFields;
        private List<Movie> moviesReturned;
    public AsignMoviesView(List<Movie> moviesReturned,List<Movie> moviesSelected) {
    	viewController = new ControllerAsignMovies(moviesSelected);
        this.moviesReturned = moviesReturned;
    	this.inputFields = new JTextField[moviesSelected.size()][2];	
        initComponents();
        setLocationRelativeTo(this);
    	generateForms();
    }
    
    private void generateForms() {
    	List<Movie> movies = viewController.getMovies();
        panelPeliculas.setLayout(new GridLayout(0, 3, 10, 10)); // 3 columnas
        for (int i = 0; i < movies.size(); i++) {
            Movie movie = movies.get(i);

            JPanel form = new JPanel();
            form.setLayout(new BoxLayout(form, BoxLayout.Y_AXIS));
            form.setBorder(BorderFactory.createTitledBorder(movie.getTitle()));

            JLabel lblCantidad = new JLabel("Cantidad:");
            JTextField txtCantidad = new JTextField(String.valueOf(movie.getCantidad()));
            txtCantidad.setMaximumSize(new Dimension(80, 25));
            txtCantidad.setPreferredSize(new Dimension(80, 25));

            JLabel lblPrecio = new JLabel("Precio:");
            JTextField txtPrecio = new JTextField(String.valueOf(movie.getPrice()));
            txtPrecio.setMaximumSize(new Dimension(80, 25));
            txtPrecio.setPreferredSize(new Dimension(80, 25));


            inputFields[i][0] = txtCantidad;
            inputFields[i][1] = txtPrecio;

            form.add(lblCantidad);
            form.add(txtCantidad);
            form.add(Box.createVerticalStrut(5));
            form.add(lblPrecio);
            form.add(txtPrecio);

            panelPeliculas.add(form);
        }

        jScrollPane1.setViewportView(panelPeliculas);
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        btn_goBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPeliculas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("Agregar peliculas");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btn_goBack.setText("Regresar");
        btn_goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goBackActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout panelPeliculasLayout = new javax.swing.GroupLayout(panelPeliculas);
        panelPeliculas.setLayout(panelPeliculasLayout);
        panelPeliculasLayout.setHorizontalGroup(
            panelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        panelPeliculasLayout.setVerticalGroup(
            panelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelPeliculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_goBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(btn_goBack))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goBackActionPerformed
        NewMoviesView nm = new NewMoviesView(moviesReturned, viewController.getMovies());
        nm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_goBackActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        List<Movie> peliculas = viewController.getMovies();
        for (int i = 0; i < peliculas.size(); i++) {
            try {
                int cantidad = Integer.parseInt(inputFields[i][0].getText().trim());
                double precio = Double.parseDouble(inputFields[i][1].getText().trim());

                peliculas.get(i).setCantidad(cantidad);
                peliculas.get(i).setPrice(precio);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Error en la película: " + peliculas.get(i).getTitle());
                return;
            }
        }
        viewController.publishNewMovies(peliculas);
        JOptionPane.showMessageDialog(this, "Películas actualizadas correctamente.");
        AdminView av = new AdminView();
        av.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignMoviesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignMoviesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignMoviesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignMoviesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panelPeliculas;
    // End of variables declaration//GEN-END:variables
}
